version: "3.9"

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - .env.mongo
    networks:
      - web

  dev:
    build: 
      dockerfile: Dockerfile.dev
    env_file:
      - $PWD/.env
    ports:
      - "8080:8080"
    volumes:
      - $PWD:/app
    restart: always
    depends_on:
      - db
    networks:
      - web

networks:
  web:
